import { Transaction } from "@/types";

export const dummyTransactions: Transaction[] = [
  {
    id: 1,
    name: "أحمد صالح",
    phone: "0599123456",
    serviceType: ["MECHANIC", "ELECTRIC"],
    location: "RAMMALLAH",
    status: "NEW",
    cost: 180,
    createdAt: new Date("2024-12-01T10:15:00"),
    notes: "فحص محرك السيارة وفحص الأسلاك الكهربائية.",
    adminNotes: "تم تحويل الطلب إلى الفني خالد.",
  },
  {
    id: 2,
    name: "مها نصار",
    phone: "+972654787223",
    serviceType: ["CIVIL"],
    location: "NABLUS",
    status: "PENDING",
    cost: 350,
    createdAt: new Date("2024-12-03T14:20:00"),
    notes: "فحص تشققات الجدران في الشقة.",
    adminNotes: "بانتظار تأكيد العميل.",
  },
  {
    id: 3,
    name: "يوسف البرغوثي",
    phone: "0599988776",
    serviceType: ["ARCHITECTURAL"],
    location: "BETHLEHEM",
    status: "FINISHED",
    cost: 900,
    createdAt: new Date("2024-11-25T09:00:00"),
    notes: "مراجعة التصميم المعماري بالكامل.",
    adminNotes: "تم التسليم بنجاح.",
  },
  {
    id: 4,
    name: "سارة حمدان",
    phone: "0597623411",
    serviceType: ["CHARGES"],
    location: "ZOOM",
    status: "PAUSED",
    cost: 120,
    createdAt: new Date("2024-12-10T16:45:00"),
    notes: "رسوم الاستشارة عبر الإنترنت بانتظار الاستكمال.",
    adminNotes: "تم الإيقاف بسبب نقص الوثائق.",
  },
  {
    id: 5,
    name: "محمود جابر",
    phone: "0569991122",
    serviceType: ["MECHANIC"],
    location: "HEBRON",
    status: "CANCELLED",
    cost: 0,
    createdAt: new Date("2024-12-02T11:30:00"),
    notes: "قام العميل بإلغاء الزيارة قبل الموعد.",
    adminNotes: "تم وضع حالة الإلغاء.",
  },
  {
    id: 6,
    name: "لينا الشريف",
    phone: "0597788990",
    serviceType: ["ELECTRIC", "CHARGES"],
    location: "SALFIT",
    status: "NEW",
    cost: 250,
    createdAt: new Date("2024-12-08T13:10:00"),
    notes: "فحص كهربائي للمنزل + رسوم استشارة.",
    adminNotes: "بانتظار الجدولة.",
  },
  {
    id: 7,
    name: "رامي خليل",
    phone: "0565544332",
    serviceType: ["CIVIL", "ARCHITECTURAL", "ELECTRIC", "MECHANIC"],
    location: "TULKAREM",
    status: "FINISHED",
    cost: 700,
    createdAt: new Date("2024-11-28T08:50:00"),
    notes: "إعادة تصميم إنشائي وداخلي.",
    adminNotes: "تمت الموافقه من قسم الجودة.",
  },
];

export const defaultTransaction: Transaction = {
  id: 0,
  name: "",
  phone: "",
  serviceType: [],
  location: "BETHLEHEM",
  status: "NEW",
  cost: 0,
  createdAt: new Date(),
  notes: "",
  adminNotes: "",
};
